### ISSUE TITLE
CliColors is missing formats.

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-cli#1]
Please support all formats as described at https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-formatting

One of my quick 'n dirty written codes:

```php
/**
 * Echo an ANSI formatted value.
 *
 * The argument must be an array with an even amount of elements.
 * The odd element values define the format, the following element contains the value to echo.
 *
 * @see https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
 *
 * @param mixed ...$arguments Format and values to echo.
 */
function echoFormatted(...$arguments)
{
    // Extract colors.
    $formats = $texts = [];
    foreach ($arguments as $key => $value) {
        $value = @(string)$value;
        if ($key % 2) {
            $texts[] = $value;
        } else {
            $formats[] = $value;
        }
    }

    if (count($formats) != count($texts)) {
        throw new InvalidArgumentException('Given formats and texts are out of balance!');
    }

    // Echo colorized texts.
    $availableFormats = [
        'default'      => 0,
        'bold'         => 1,
        'underlineYes' => 4,
        'underlineNo'  => 24,
        'negative'     => 7,
        'positive'     => 27,

        'fBlack'    => 30,
        'fRed'      => 31,
        'fGreen'    => 32,
        'fYellow'   => 33,
        'fBlue'     => 34,
        'fMagenta'  => 35,
        'fCyan'     => 36,
        'fWhite'    => 37,
        'fExtended' => 38,
        'fDefault'  => 39,

        'bBlack'    => 40,
        'bRed'      => 41,
        'bGreen'    => 42,
        'bYellow'   => 43,
        'bBlue'     => 44,
        'bMagenta'  => 45,
        'bCyan'     => 46,
        'bWhite'    => 47,
        'bExtended' => 48,
        'bDefault'  => 49,

        'fbBlack'   => 90,
        'fbRed'     => 91,
        'fbGreen'   => 92,
        'fbYellow'  => 93,
        'fbBlue'    => 94,
        'fbMagenta' => 95,
        'fbCyan'    => 96,
        'fbWhite'   => 97,

        'bbBlack'   => 100,
        'bbRed'     => 101,
        'bbGreen'   => 102,
        'bbYellow'  => 103,
        'bbBlue'    => 104,
        'bbMagenta' => 105,
        'bbCyan'    => 106,
        'bbWhite'   => 107,
    ];

    for ($i = 0; $i < count($formats); $i++) {
        echo "\033[{$availableFormats[$formats[$i]]}m", $texts[$i], "\033[0m";
    }
}

```

**Comment by JBlond** [comment]
Well, I used the 8 bit proof colors for terminals https://misc.flogisoft.com/bash/tip_colors_and_formatting#terminals_compatibility

**Comment by DigiLive** [comment]
I see... It's not a problem anyway, just thought it would be a nice addition.

Maybe you can add them and keep backwards compatibility. If not, it's ok for me as well. 😊

**Comment by JBlond** [comment]
It tried all those new colors. And they did not work. Not on the linux shell, nor on windows cmd nor on cmd in the new windows terminal app (which supports UTF-8 and emoji).

**Comment by DigiLive** [comment]
As I'm working on a Windows OS...
Support for ANSI escape sequences in console windows was not added until Windows 10 Threshold 2 (TH2), also known as the "November Update", which is version 1511 and has the build number 10586.
It might even be the escape sequences must be enabled manually.

As a workaround on downlevel systems, you could use ANSICon or ConEmu.
https://github.com/adoxa/ansicon/
https://sourceforge.net/projects/conemu/

**Comment by JBlond** [comment]
I tried conEmu, Same result.

**Comment by DigiLive** [comment]
How strange...
With or without AnsiCon at Microsoft Windows [Version 10.0.18363.900], I get the following at cmd and Git Bash Shell:
![ANSI Output](https://user-images.githubusercontent.com/7613487/87577094-aad8fb00-c6d2-11ea-98a2-4ae431e3b5a5.png)

**Comment by JBlond** [comment]
You are welcome to open a PR.

**Comment by JBlond** [comment]
Can you try

```bash
for code in {0..255}
    do echo -e "\e[38;5;${code}m"'\\e[38;5;'"$code"m"\e[0m"
  done
```

**Comment by DigiLive** [comment]
I keep my scripting to php 😅
```php
for ($i=0;$i<256;$i++) {
    echo "\033[{$i}m", $i, "\033[0m | ";
}
```
results, consistent with my first post, into:
![afbeelding](https://user-images.githubusercontent.com/7613487/110606807-d9887200-818a-11eb-93da-38750c089115.png)

**Comment by JBlond** [comment]
Hm, most of them are just "normal" color.  That is one reason I have only the "save" colors in the class.

**Comment by JBlond** [comment]
Won't do. I tried a lot of combinations and those color aren't visible or mess with bash, fish, zsh.
